"use client";

import { useEffect, useMemo, useState } from "react";
import type { Repo } from "@/lib/github";

type ContributionDay = { contributionCount: number; date: string };
type Calendar = { totalContributions: number; weeks: { contributionDays: ContributionDay[] }[] };

const skills = [["Python","Programming"],["SQL","Data"],["FastAPI","Backend"],["React","Frontend"],["PyTorch","ML"],["XGBoost","ML"],["RAG","AI"],["Docker","DevOps"],["Kubernetes","Cloud"],["PostgreSQL","Database"],["GitHub Actions","CI/CD"],["MLflow","MLOps"]];
const projects = [
  { repo:"Data-Leakage-Detection-System", eyebrow:"AI / ML", title:"LeakShield", text:"An ML pipeline integrity platform that detects dataset leakage, audits preprocessing pipelines, explains violations, and visualizes risk.", metric:"6 detectors · 20 API endpoints", image:"https://opengraph.githubassets.com/1/Sukumar-Elley/Data-Leakage-Detection-System" },
  { repo:"Event-driven-agentic-platform-", eyebrow:"Distributed AI", title:"Agentic System", text:"A production-oriented event-driven agent platform with a Rust Raft broker, Python agents, multimodal processing, observability, chaos testing and Kubernetes.", metric:"6 production phases", image:"https://opengraph.githubassets.com/1/Sukumar-Elley/Event-driven-agentic-platform-" },
  { repo:"ecommerce-retention", eyebrow:"ML / MLOps", title:"RetentionAI", text:"Enterprise retention engineering across churn prediction, uplift modeling, recommendations, RL pricing, RAG agents and drift monitoring.", metric:"25+ API endpoints", image:"https://opengraph.githubassets.com/1/Sukumar-Elley/ecommerce-retention" }
];

function AnimatedNumber({ value, suffix="" }: { value:number; suffix?:string }) {
  const [shown,setShown]=useState(0);
  useEffect(()=>{let frame=0;const start=performance.now();const tick=(now:number)=>{const p=Math.min(1,(now-start)/900);setShown(Math.round(value*(1-Math.pow(1-p,3))));if(p<1)frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[value]);
  return <>{shown.toLocaleString()}{suffix}</>;
}

function Contributions(){
  const [calendar,setCalendar]=useState<Calendar|null>(null);
  useEffect(()=>{fetch("/api/github").then(r=>r.json()).then(setCalendar).catch(()=>{})},[]);
  const cells=useMemo(()=>calendar?.weeks.flatMap(w=>w.contributionDays)||[],[calendar]);
  return <div className="contrib-wrap"><div className="contrib-head"><span>GitHub activity</span><strong>{calendar?<AnimatedNumber value={calendar.totalContributions}/>:"—"} contributions</strong></div><div className="contrib-grid">{cells.map(day=><span key={day.date} title={`${day.contributionCount} contributions on ${day.date}`} className={`level-${Math.min(4,Math.ceil(day.contributionCount/3))}`}/>)}{!cells.length&&Array.from({length:180}).map((_,i)=><span key={i} className="level-0"/>)}</div>{!calendar&&<p className="contrib-note">Add <code>GITHUB_TOKEN</code> in production to enable the live contribution calendar.</p>}</div>;
}

function ContactForm(){
  const [state,setState]=useState<"idle"|"sending"|"sent"|"error">("idle");
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setState("sending");const form=new FormData(e.currentTarget);try{const response=await fetch("/api/contact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(form.entries()))});if(!response.ok)throw new Error();e.currentTarget.reset();setState("sent")}catch{setState("error")}}
  return <form className="contact-form" onSubmit={submit}><input name="website" tabIndex={-1} autoComplete="off" className="honeypot"/><label>Name<input name="name" required minLength={2} placeholder="Your name"/></label><label>Email<input name="email" required type="email" placeholder="you@company.com"/></label><label>Message<textarea name="message" required minLength={10} rows={6} placeholder="Tell me what you're building..."/></label><button className="button primary" disabled={state==="sending"}>{state==="sending"?"Sending…":state==="sent"?"Message sent ✓":"Send message ↗"}</button>{state==="error"&&<p className="form-error">Could not send. Check the server environment variables.</p>}</form>;
}

export function PortfolioClient({initialRepos}:{initialRepos:Repo[]}){
  const [theme,setTheme]=useState<"dark"|"light">("dark");const [active,setActive]=useState("All");
  useEffect(()=>{const saved=localStorage.getItem("theme") as "dark"|"light"|null;if(saved)setTheme(saved)},[]);
  useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem("theme",theme)},[theme]);
  const visibleRepos=active==="All"?initialRepos:initialRepos.filter(r=>(r.language||"").toLowerCase().includes(active.toLowerCase()));
  return <div>
    <header className="nav"><a className="logo" href="#home"><span>SE</span> SUKUMAR ELLEY</a><nav><a href="#work">Work</a><a href="#about">About</a><a href="#stack">Stack</a><a href="#contact">Contact</a></nav><div className="nav-right"><a className="resume" href="/Sukumar-Elley-Resume.pdf" download>Resume ↓</a><button className="theme" onClick={()=>setTheme(theme==="dark"?"light":"dark")} aria-label="Toggle theme">{theme==="dark"?"☼":"☾"}</button></div></header>
    <main>
      <section className="hero" id="home"><div className="hero-grid"><div><p className="eyebrow"><span className="pulse"/> DATA · AI · SOFTWARE</p><h1>Engineering<br/><em>intelligence</em><br/>that ships.</h1><p className="hero-copy">I’m <strong>Sukumar Elley</strong> — a data and AI-focused engineer building analytical systems, production ML platforms, and full-stack products.</p><div className="actions"><a className="button primary" href="#work">Explore work ↘</a><a className="button" href="#contact">Start a conversation ↗</a></div></div><div className="hero-console"><div className="console-top"><i/><i/><i/><span>~/sukumar</span></div><div className="console-body"><p><b>$</b> whoami</p><strong>sukumar_elley</strong><p><b>$</b> focus</p><strong>data · ai · systems</strong><p><b>$</b> ship()</p><strong className="green">production_ready<span className="cursor">_</span></strong></div><div className="console-chip chip-a">Python</div><div className="console-chip chip-b">RAG / ML</div><div className="console-chip chip-c">FastAPI</div></div></div><div className="hero-bottom"><span>BASED IN INDIA</span><span>OPEN TO OPPORTUNITIES</span><span>2026 →</span></div></section>
      <section className="ticker"><div>PYTHON ✦ MACHINE LEARNING ✦ DATA ENGINEERING ✦ AI SYSTEMS ✦ FASTAPI ✦ REACT ✦ MLOPS ✦ PYTHON ✦ MACHINE LEARNING ✦</div></section>
      <section className="stats section"><div><strong><AnimatedNumber value={initialRepos.length} suffix="+"/></strong><span>featured GitHub projects</span></div><div><strong>AI</strong><span>production systems</span></div><div><strong>ML</strong><span>analytics + modeling</span></div><div><strong>∞</strong><span>things left to build</span></div></section>
      <section className="section" id="work"><div className="section-label">01 / SELECTED WORK</div><div className="section-heading"><h2>Built to be <em>useful.</em></h2><p>Real repositories from my GitHub, surfaced dynamically and linked directly to the source.</p></div><div className="featured-grid">{projects.map(p=><article className="featured-card" key={p.repo}><a href={`https://github.com/Sukumar-Elley/${p.repo}`} target="_blank" rel="noreferrer"><div className="project-image"><img src={p.image} alt={`${p.title} GitHub project preview`}/><div className="image-overlay">OPEN REPOSITORY ↗</div></div><div className="card-copy"><div><span>{p.eyebrow}</span><h3>{p.title}</h3></div><b>{p.metric}</b><p>{p.text}</p></div></a></article>)}</div><div className="repo-toolbar"><div><span>GitHub repositories</span><strong>Live from github.com/Sukumar-Elley</strong></div><div className="filters">{["All","Python","JavaScript","Rust"].map(x=><button className={active===x?"active":""} key={x} onClick={()=>setActive(x)}>{x}</button>)}</div></div><div className="repo-grid">{visibleRepos.map(repo=><a className="repo-card" href={repo.url} target="_blank" rel="noreferrer" key={repo.name}><div className="repo-head"><span className="repo-icon">↗</span><span>{repo.language||"Repository"}</span></div><h3>{repo.name.replaceAll("-"," ")}</h3><p>{repo.description}</p><div className="repo-foot"><span>★ {repo.stars}</span><span>⑂ {repo.forks}</span><span>Updated {repo.updatedAt?new Date(repo.updatedAt).toLocaleDateString("en-IN",{month:"short",year:"numeric"}):"—"}</span></div></a>)}</div></section>
      <section className="section about-grid" id="about"><div className="section-label">02 / ABOUT</div><div><h2>Curious by default.<br/><em>Practical</em> by design.</h2><div className="about-text"><p>My work sits between data analysis, machine learning, backend engineering and product thinking. I like understanding the problem deeply, then building the smallest reliable system that makes the answer useful.</p><p>Recent work spans leakage detection, distributed agentic systems, retention intelligence, APIs, MLOps, RAG and cloud-native deployment.</p></div></div></section>
      <section className="section" id="stack"><div className="section-label">03 / TOOLKIT</div><div className="section-heading"><h2>The stack <em>behind</em> the work.</h2><p>Technologies drawn from current projects and resume.</p></div><div className="skill-grid">{skills.map(([name,group])=><div className="skill" key={name}><span>{group}</span><strong>{name}</strong></div>)}</div><Contributions/></section>
      <section className="experience section"><div className="section-label">04 / EXPERIENCE</div><div className="timeline"><div><small>DEC 2025 — FEB 2026</small><h3>Software Engineer Intern · BlueStock FinTech</h3><p>Production backend services, API integrations, microservice architecture, FastAPI, Docker/Kubernetes and CI/CD.</p></div><div><small>AUG 2024 — OCT 2024</small><h3>Data Science Intern · Interns Elite</h3><p>Supervised and unsupervised ML, anomaly detection, preprocessing pipelines, EDA dashboards and model reporting.</p></div><div><small>2023 — 2027</small><h3>B.Tech · Computer Science (Data Science)</h3><p>MLR Institute of Technology · CGPA 7.8 · Project Expo Winner, 2025.</p></div></div></section>
      <section className="contact section" id="contact"><div className="section-label">05 / CONTACT</div><div className="contact-layout"><div><p className="eyebrow">HAVE A PROBLEM WORTH SOLVING?</p><h2>Let’s build<br/><em>something good.</em></h2><div className="links"><a href="mailto:sukumarelley13431@gmail.com">sukumarelley13431@gmail.com ↗</a><a href="https://github.com/Sukumar-Elley" target="_blank" rel="noreferrer">GitHub ↗</a><a href="https://www.linkedin.com/in/sukumar-elley" target="_blank" rel="noreferrer">LinkedIn ↗</a></div></div><ContactForm/></div></section>
    </main><footer><span>© {new Date().getFullYear()} SUKUMAR ELLEY</span><span>DATA · AI · SOFTWARE</span><span>BUILT WITH NEXT.JS</span></footer>
  </div>;
}